# Docker compose override for local development environment

services:
  only-paws-app:
    ports:
      - "8000:8000"
    volumes:
      - ../api:/api
      - ../api/media:/api/media  # Local media storage
      - ../logs/django-dev.log:/vol/log/django.log
    env_file:
      - dev/.env.dev.local
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py load_report_reasons &&
             python manage.py load_pet_types &&
             python manage.py runserver 0.0.0.0:8000"

  only-paws-db:
    volumes:
      - only-paws-db-data-dev:/var/lib/postgresql/data
    env_file:
      - dev/.env.dev.local.db

volumes:
  only-paws-db-data-dev: