# Generated by Django 5.1.1 on 2025-11-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key for the configuration setting', max_length=100, unique=True)),
                ('value', models.JSONField(help_text='JSON value for the configuration')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the configuration was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the configuration was last updated')),
            ],
            options={
                'verbose_name': 'App Configuration',
                'verbose_name_plural': 'App Configurations',
                'ordering': ['key'],
            },
        ),
    ]
