# Generated by Django 5.2.12 on 2026-04-26 15:48

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile_app", "0011_regularprofile_anxiety_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePreferenceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=512,
                        help_text="Weighted-average embedding of the profile's recent post interactions.",
                        null=True,
                    ),
                ),
                ("last_computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interaction_count_at_last_compute",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "embedding_model",
                    models.CharField(default="clip-vit-base-patch32", max_length=100),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference_embedding",
                        to="profile_app.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_computed_at"],
                        name="recommendat_last_co_c08239_idx",
                    )
                ],
            },
        ),
    ]
