# Generated by Django 5.2.12 on 2026-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepreferenceembedding',
            name='embedding_model',
            field=models.CharField(default='sentence-transformers/clip-ViT-B-32', max_length=100),
        ),
    ]
