name: only-paws

# Base docker compose file for all environments
# Each environment has a docker-compose.override.yml file that extends this file

services:
  only-paws-app:
    container_name: onlypaws_django
    build:
      context: ../
    depends_on:
      - only-paws-db
    restart: unless-stopped

  only-paws-db:
    container_name: onlypaws_db
    image: postgres:16-alpine
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  log_volume:

