# Docker compose override for production environment

services:
  only-paws-app:
    volumes:
      - ../api:/api
      - static_volume:/api/static
      - ../logs:/vol/log
    env_file:
      - prod/.env.prod
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py load_report_reasons &&
             python manage.py load_pet_types &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"

  only-paws-db:
    volumes:
      - prod_db_volume:/var/lib/postgresql/data
    env_file:
      - prod/.env.prod.db

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/vol/web/static:ro
      - ../nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - only-paws-app

volumes:
  prod_db_volume:
  static_volume: