# Generated by Django 5.1.1 on 2025-11-06 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='profile_app.profile'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='address',
            field=models.OneToOneField(blank=True, help_text='Business address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profile', to='profile_app.address'),
        ),
        migrations.AddField(
            model_name='regularprofile',
            name='pet_type',
            field=models.ForeignKey(blank=True, help_text='Type of pet (dog, cat, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_profiles', to='profile_app.pettype'),
        ),
    ]
