# Generated by Django 5.1.1 on 2026-01-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If true, only approved followers can see posts'),
        ),
    ]
