# Generated by Django 5.1.1 on 2026-02-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_public_id_default'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profileimagescaled',
            new_name='profile_app_profile_c9d9c7_idx',
            old_name='profile_app_profile_8a1b2c_idx',
        ),
    ]
