# Generated by Django 5.2.12 on 2026-03-20 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_rename_profile_app_profile_8a1b2c_idx_profile_app_profile_c9d9c7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 20, 22, 19, 0, 875741, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pettype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 20, 22, 19, 18, 450506, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
