# Generated by Django 5.2.12 on 2026-04-07 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_address_created_at_pettype_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularprofile',
            name='anxiety_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='', help_text='Anxiety level of the pet', max_length=6),
        ),
        migrations.AddField(
            model_name='regularprofile',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Birthdate of the pet', null=True),
        ),
        migrations.AddField(
            model_name='regularprofile',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='', help_text='Energy level of the pet', max_length=6),
        ),
        migrations.AddField(
            model_name='regularprofile',
            name='is_service_animal',
            field=models.BooleanField(blank=True, help_text='Whether the pet is a service animal', null=True),
        ),
        migrations.AddField(
            model_name='regularprofile',
            name='is_spayed_neutered',
            field=models.BooleanField(blank=True, help_text='Whether the pet has been spayed or neutered', null=True),
        ),
        migrations.AddField(
            model_name='regularprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='', help_text='Sex of the pet', max_length=6),
        ),
        migrations.AddField(
            model_name='regularprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight of the pet in pounds', null=True, validators=[django.core.validators.MaxValueValidator(2500)]),
        ),
    ]
