# Generated by Django 5.1.1 on 2025-10-30 16:27

import apps.user_app.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('street_address_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('full_address_text', models.TextField(blank=True, default='', help_text="Full address as text. Use this for international addresses that don't fit the standard fields.")),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('about', models.CharField(blank=True, default='', help_text='DEPRECATED: Will be moved to RegularProfile/BusinessProfile', max_length=1000)),
                ('name', models.CharField(blank=True, default='', help_text='DEPRECATED: Will be moved to RegularProfile', max_length=64)),
                ('breed', models.CharField(blank=True, default='', help_text='DEPRECATED: Will be moved to RegularProfile', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
                ('pet_type', models.ForeignKey(blank=True, help_text='DEPRECATED: Will be moved to RegularProfile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_profiles', to='user_app.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.user_app.models.profile_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='user_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyEmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verify_email_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_app.profile')),
                ('about_new', models.CharField(blank=True, default='', help_text='About this business profile', max_length=2000)),
                ('business_name', models.CharField(help_text='Official business name', max_length=100)),
                ('business_category', models.CharField(choices=[('VETERINARY', 'Veterinary Clinic'), ('SHELTER', 'Animal Shelter'), ('RESCUE', 'Animal Rescue'), ('GROOMING', 'Pet Grooming'), ('TRAINING', 'Pet Training'), ('PET_STORE', 'Pet Store'), ('BREEDER', 'Breeder'), ('BOARDING', 'Pet Boarding'), ('DAYCARE', 'Pet Daycare'), ('PET_SITTING', 'Pet Sitting'), ('PHOTOGRAPHY', 'Pet Photography'), ('WALKER', 'Pet Walker'), ('OTHER', 'Other Pet Business')], default='OTHER', help_text='Type of pet business', max_length=20)),
                ('website', models.URLField(blank=True, default='', help_text='Business website URL')),
                ('phone', models.CharField(blank=True, default='', help_text='Business phone number', max_length=20)),
                ('verified', models.BooleanField(default=False, help_text='Whether the business has been verified by admin')),
                ('subscription_tier', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='FREE', help_text='Business subscription tier', max_length=20)),
                ('analytics_enabled', models.BooleanField(default=False, help_text='Whether analytics tracking is enabled for this business')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Business operating hours in JSON format')),
                ('address', models.OneToOneField(blank=True, help_text='Business address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profile', to='user_app.address')),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
            },
            bases=('user_app.profile',),
        ),
        migrations.CreateModel(
            name='RegularProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_app.profile')),
                ('about_new', models.CharField(blank=True, default='', help_text='About this pet profile', max_length=1000)),
                ('name_new', models.CharField(blank=True, default='', help_text='Name of the pet', max_length=64)),
                ('breed_new', models.CharField(blank=True, default='', help_text='Breed of the pet', max_length=64)),
                ('pet_type_new', models.ForeignKey(blank=True, help_text='Type of pet (dog, cat, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_profiles', to='user_app.pettype')),
            ],
            options={
                'verbose_name': 'Regular Profile',
                'verbose_name_plural': 'Regular Profiles',
            },
            bases=('user_app.profile',),
        ),
        migrations.CreateModel(
            name='PendingEmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('verification_token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'new_email')},
            },
        ),
    ]
