# Generated by Django 5.1.1 on 2025-11-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        # First, remove fields from parent Profile class
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pet_type',
        ),
        # Then, rename fields in child classes (now safe because parent fields are gone)
        migrations.RenameField(
            model_name='businessprofile',
            old_name='about_new',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='regularprofile',
            old_name='about_new',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='regularprofile',
            old_name='breed_new',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='regularprofile',
            old_name='name_new',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='regularprofile',
            old_name='pet_type_new',
            new_name='pet_type',
        ),
    ]
