# Generated by Django 5.1.1 on 2026-02-21 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_backfill_email_auth_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authprovider",
            options={},
        ),
        migrations.RenameIndex(
            model_name="authprovider",
            new_name="user_app_au_provide_abaed7_idx",
            old_name="user_app_authprovider_prov_ext_idx",
        ),
        migrations.AlterUniqueTogether(
            name="pendingemailchange",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="pendingemailchange",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
