# Generated by Django 5.2.12 on 2026-03-20 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_authprovider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 20, 22, 19, 29, 271861, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
