# Generated by Django 5.2.12 on 2026-04-03 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAccountDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_account_deletion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
