# Generated by Django 5.1.1 on 2025-09-18 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0024_add_postimage_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('system', 'System')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('post', models.ForeignKey(blank=True, help_text='Related post (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core_app.post')),
                ('recipient', models.ForeignKey(help_text='Profile that receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='core_app.profile')),
                ('sender', models.ForeignKey(blank=True, help_text='Profile that triggered the notification (can be null for system notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='core_app.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_0f4137_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_cebaba_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f7ef6c_idx')],
            },
        ),
    ]
