# Generated by Django 5.1.1 on 2025-10-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like_post', 'Like Post'), ('like_comment', 'Like Comment'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('follow', 'Follow'), ('mention', 'Mention'), ('system', 'System')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('comment', models.ForeignKey(blank=True, help_text='Related comment (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='interactions_app.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
