# Generated by Django 5.1.1 on 2025-11-06 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications_app', '0001_initial'),
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Related post (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts_app.post'),
        ),
    ]
