# Generated by Django 5.1.1 on 2025-09-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_add_postimage_embedding'),
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Related comment (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core_app.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Like Post'), ('like_comment', 'Like Comment'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('system', 'System')], help_text='Type of notification', max_length=20),
        ),
    ]
