# Generated by Django 5.1.1 on 2025-10-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications_app', '0002_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='Profile that receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Profile that triggered the notification (can be null for system notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='user_app.profile'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_0f4137_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_cebaba_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f7ef6c_idx'),
        ),
    ]
