# Generated by Django 5.1.1 on 2025-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_notification_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Like Post'), ('like_comment', 'Like Comment'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('follow', 'Follow'), ('mention', 'Mention'), ('system', 'System')], help_text='Type of notification', max_length=20),
        ),
    ]
