# Generated by Django 5.1.1 on 2026-01-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Like Post'), ('like_comment', 'Like Comment'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('follow', 'Follow'), ('mention', 'Mention'), ('tagged_post', 'Tagged in Post'), ('system', 'System')], help_text='Type of notification', max_length=20),
        ),
    ]
