# Generated by Django 5.1.1 on 2026-01-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Like Post'), ('like_comment', 'Like Comment'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_request_accepted', 'Follow Request Accepted'), ('mention', 'Mention'), ('tagged_post', 'Tagged in Post'), ('system', 'System')], help_text='Type of notification', max_length=30),
        ),
    ]
