# Generated by Django 5.1.1 on 2025-10-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions_app', '0002_initial'),
        ('posts_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions_app.comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='interactions_app.comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts_app.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='user_app.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('profile', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followed', 'followed_by')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('profile', 'post')},
        ),
    ]
