# Generated by Django 5.2.12 on 2026-04-26 04:57

import django.core.validators
import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions_app', '0004_followrequest'),
        ('posts_app', '0013_postimage_created_at'),
        ('profile_app', '0011_regularprofile_anxiety_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, unique=True)),
                ('interaction_type', models.CharField(choices=[('preview_click', 'Preview Click'), ('view', 'View'), ('like', 'Like'), ('save', 'Save'), ('comment', 'Comment')], max_length=32)),
                ('dwell_time_ms', models.PositiveIntegerField(blank=True, help_text='Time spent on the post in milliseconds. Only populated for VIEW interactions.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='posts_app.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to='profile_app.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', '-created_at'], name='interaction_profile_b031bb_idx'), models.Index(fields=['post', '-created_at'], name='interaction_post_id_897b39_idx')],
            },
        ),
    ]
