# Generated by Django 5.2.12 on 2026-04-26 17:00

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions_app', '0005_postinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraction',
            name='public_id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, unique=True),
        ),
    ]
