# Docker compose override for staging environment

services:
  only-paws-app:
    volumes:
      - ../api:/api
      - static_volume:/api/static
      - ../logs:/vol/log
    env_file:
      - staging/.env.staging
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py load_report_reasons &&
             python manage.py load_pet_types &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"

  only-paws-db:
    volumes:
      - staging_db_volume:/var/lib/postgresql/data
    env_file:
      - staging/.env.staging.db

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/vol/web/static:ro
      - ./staging/certbot/conf:/etc/letsencrypt:ro
      - ./staging/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - only-paws-app
    environment:
      - DOMAIN=api-staging.onlypawsapp.com

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./staging/certbot/www:/var/www/certbot
      - ./staging/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  staging_db_volume:
  static_volume: