# Generated by Django 5.1.1 on 2025-10-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation_app', '0002_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_posts', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moderation_app.reportreason'),
        ),
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('post', 'reporter')},
        ),
    ]
