# Generated by Django 5.1.1 on 2026-02-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0003_initial'),
        ('profile_app', '0009_rename_profile_app_profile_8a1b2c_idx_profile_app_profile_c9d9c7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfanityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('content_type', models.CharField(choices=[('CAPTION', 'Caption'), ('COMMENT', 'Comment'), ('USERNAME', 'Username'), ('ABOUT', 'About Text'), ('NAME', 'Name'), ('BREED', 'Breed'), ('PRE_UPLOAD_CHECK', 'Pre-Upload Text Check')], max_length=20)),
                ('detection_method', models.CharField(choices=[('ML', 'ML Probability'), ('WORD_MATCH', 'Exact Word Match'), ('SUBSTRING', 'Substring Match'), ('SHORT_MATCH', 'Start/End Match'), ('FUZZY', 'Fuzzy Match')], max_length=20)),
                ('detection_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profanity_logs', to='profile_app.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type'], name='moderation__content_25e9aa_idx'), models.Index(fields=['detection_method'], name='moderation__detecti_0ba305_idx'), models.Index(fields=['created_at'], name='moderation__created_b6b7ca_idx')],
            },
        ),
    ]
