# Generated by Django 5.1.1 on 2026-03-05 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation_app", "0007_alter_postreport_reporter"),
        (
            "profile_app",
            "0009_rename_profile_app_profile_8a1b2c_idx_profile_app_profile_c9d9c7_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to="profile_app.profile",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_given",
                        to="profile_app.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["blocker"], name="moderation__blocker_ebb868_idx"
                    ),
                    models.Index(
                        fields=["blocked"], name="moderation__blocked_a94895_idx"
                    ),
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
