# Generated by Django 5.2.12 on 2026-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation_app", "0008_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomBannedWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="WhitelistedWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["word"],
            },
        ),
    ]
