# Generated by Django 5.1.1 on 2024-10-13 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0003_alter_follow_unique_together_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileimage",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="core_app.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("profile", "post")},
        ),
    ]
