# Generated by Django 5.1.1 on 2024-12-23 01:27

import apps.core_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_comment_reply_to_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=apps.core_app.models.post_image_path),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to=apps.core_app.models.profile_image_path),
        ),
        migrations.CreateModel(
            name='PostImageStaged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_uuid', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=apps.core_app.models.post_image_staging_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_images', to='core_app.profile')),
            ],
        ),
    ]
