# Generated by Django 5.1.1 on 2024-12-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimagestaged',
            name='post_uuid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together={('profile', 'post')},
        ),
    ]
