# Generated by Django 5.1.1 on 2024-12-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_alter_postimagestaged_post_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
