# Generated by Django 5.1.1 on 2025-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_alter_profile_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
