# Generated by Django 5.1.1 on 2025-01-08 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_reportreason_postreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to='core_app.profile'),
        ),
    ]
