# Generated by Django 5.1.1 on 2025-08-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0022_pendingemailchange"),
    ]

    operations = [
        # Enable pgvector extension for similarity search
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector CASCADE;",
        ),
    ]
