# Generated by Django 5.1.1 on 2025-08-30 19:59

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='Vector embedding for similarity search', null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the embedding was generated', null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='embedding_model',
            field=models.CharField(default='clip-vit-base-patch32', help_text='Model used to generate the embedding', max_length=100),
        ),
    ]
