# Generated by Django 5.1.1 on 2025-09-28 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_add_postimage_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000, message='Caption cannot exceed 1000 characters.')]),
        ),
    ]
