# Generated by Django 5.1.1 on 2025-10-24 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_alter_post_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('street_address_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('full_address_text', models.TextField(blank=True, default='', help_text="Full address as text. Use this for international addresses that don't fit the standard fields.")),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: Will be moved to RegularProfile/BusinessProfile', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='breed',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: Will be moved to RegularProfile', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: Will be moved to RegularProfile', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pet_type',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Will be moved to RegularProfile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_profiles', to='core_app.pettype'),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.profile')),
                ('about_new', models.CharField(blank=True, default='', help_text='About this business profile', max_length=2000)),
                ('business_name', models.CharField(help_text='Official business name', max_length=100)),
                ('business_category', models.CharField(choices=[('VETERINARY', 'Veterinary Clinic'), ('SHELTER', 'Animal Shelter'), ('RESCUE', 'Animal Rescue'), ('GROOMING', 'Pet Grooming'), ('TRAINING', 'Pet Training'), ('PET_STORE', 'Pet Store'), ('BREEDER', 'Breeder'), ('BOARDING', 'Pet Boarding'), ('DAYCARE', 'Pet Daycare'), ('PET_SITTING', 'Pet Sitting'), ('PHOTOGRAPHY', 'Pet Photography'), ('WALKER', 'Pet Walker'), ('OTHER', 'Other Pet Business')], default='OTHER', help_text='Type of pet business', max_length=20)),
                ('website', models.URLField(blank=True, default='', help_text='Business website URL')),
                ('phone', models.CharField(blank=True, default='', help_text='Business phone number', max_length=20)),
                ('verified', models.BooleanField(default=False, help_text='Whether the business has been verified by admin')),
                ('subscription_tier', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='FREE', help_text='Business subscription tier', max_length=20)),
                ('analytics_enabled', models.BooleanField(default=False, help_text='Whether analytics tracking is enabled for this business')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Business operating hours in JSON format')),
                ('address', models.OneToOneField(blank=True, help_text='Business address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profile', to='core_app.address')),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
            },
            bases=('core_app.profile',),
        ),
        migrations.CreateModel(
            name='RegularProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.profile')),
                ('about_new', models.CharField(blank=True, default='', help_text='About this pet profile', max_length=1000)),
                ('name_new', models.CharField(blank=True, default='', help_text='Name of the pet', max_length=64)),
                ('breed_new', models.CharField(blank=True, default='', help_text='Breed of the pet', max_length=64)),
                ('pet_type_new', models.ForeignKey(blank=True, help_text='Type of pet (dog, cat, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_profiles', to='core_app.pettype')),
            ],
            options={
                'verbose_name': 'Regular Profile',
                'verbose_name_plural': 'Regular Profiles',
            },
            bases=('core_app.profile',),
        ),
    ]
