# Generated by Django 5.1.1 on 2025-10-24 12:44

from django.db import migrations
from django.utils import timezone


def migrate_profile_data_to_regular_profiles(apps, schema_editor):
    """
    Create RegularProfile instances for all existing Profile records
    and copy data from legacy fields to new fields.
    """
    Profile = apps.get_model('core_app', 'Profile')
    
    # Use raw SQL to insert into RegularProfile table
    # This avoids the ORM trying to create a new parent Profile
    with schema_editor.connection.cursor() as cursor:
        profiles = Profile.objects.all()
        
        for profile in profiles:
            # Check if RegularProfile already exists
            cursor.execute(
                "SELECT COUNT(*) FROM core_app_regularprofile WHERE profile_ptr_id = %s",
                [profile.id]
            )
            if cursor.fetchone()[0] > 0:
                print(f"Profile {profile.username} already has RegularProfile, skipping")
                continue
            
            # Check if BusinessProfile already exists
            cursor.execute(
                "SELECT COUNT(*) FROM core_app_businessprofile WHERE profile_ptr_id = %s",
                [profile.id]
            )
            if cursor.fetchone()[0] > 0:
                print(f"Profile {profile.username} already has BusinessProfile, skipping")
                continue
            
            # Insert directly into RegularProfile table
            pet_type_id = profile.pet_type.id if profile.pet_type else None
            cursor.execute(
                """
                INSERT INTO core_app_regularprofile 
                    (profile_ptr_id, about_new, name_new, pet_type_new_id, breed_new)
                VALUES (%s, %s, %s, %s, %s)
                """,
                [
                    profile.id,
                    profile.about or '',
                    profile.name or '',
                    pet_type_id,
                    profile.breed or '',
                ]
            )
            print(f"Migrated profile: {profile.username}")


def reverse_migration(apps, schema_editor):
    """Delete all RegularProfile instances."""
    RegularProfile = apps.get_model('core_app', 'RegularProfile')
    RegularProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0026_address_profile_created_at_profile_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_profile_data_to_regular_profiles,
            reverse_migration
        ),
    ]
