# Generated by Django 5.1.1 on 2025-10-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0027_migrate_profiles_to_regular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order of the image in the post'),
        ),
    ]
