# Generated by Django 5.1.1 on 2025-10-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0028_alter_postimage_options_postimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='is_main',
        ),
    ]
