"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from typing import Literal
from celery.schedules import crontab
from . import unfold_settings
from .utils import print_environment_banner

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-06#hk8o*8!t(7)v&ydcto7+-iz)1npn%2628+$@zy*@fo7@r79"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if os.environ.get("DEBUG") == "True":
    DEBUG = True


ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    "content-disposition",
    "accept-encoding",
    "content-type",
    "accept",
    "origin",
    "authorization",
    "auth-profile-id",
    "x-client-type",  # Used to distinguish between web and mobile clients
]
CORS_ALLOW_CREDENTIALS = True  # Required for cookies to be sent cross-origin

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "https://api-staging.onlypawsapp.com",
    "https://api.onlypawsapp.com",
    "https://onlypawsapp.com",
]
CSRF_ALLOWED_ORIGINS = [
    "https://api-staging.onlypawsapp.com",
    "https://api.onlypawsapp.com",
    "https://onlypawsapp.com",
]
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "Lax"

# Exempt API endpoints from CSRF
CSRF_EXEMPT_PATHS = [
    "/api/",
    "/docs/",
    "/schema/",
]

# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "channels",
    "apps.core_app",
    "apps.user_app",
    "apps.profile_app",
    "apps.posts_app",
    "apps.interactions_app",
    "apps.moderation_app",
    "apps.feedback_app",
    "apps.notifications_app",
    "apps.config_app",
    "apps.announcements_app",
    "apps.admin_app",
    "apps.legal_app",
    "storages",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",  # Required for token blacklisting/rotation
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "apps.core_app.middleware.CustomCsrfMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.core_app.middleware.MaintenanceModeMiddleware",  # After auth for admin bypass
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.core_app.middleware.ProfileAuthenticationMiddleware",
    "apps.core_app.logging_middleware.RequestLoggingMiddleware",  # HTTP request logging
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Default to sqlite3 database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets"),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "user_app.User"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "apps.core_app.exceptions.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "auth": "30/minute",
        "auth_sensitive": "5/minute",
    },
}

access_token_lifetime = int(os.environ.get("ACCESS_TOKEN_LIFETIME", "15"))
refresh_token_lifetime = int(os.environ.get("REFRESH_TOKEN_LIFETIME", "7"))

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=access_token_lifetime),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=refresh_token_lifetime),
    # Token rotation - generate new refresh token on each refresh
    "ROTATE_REFRESH_TOKENS": True,
    # Blacklist old tokens after rotation for security
    "BLACKLIST_AFTER_ROTATION": True,
    # Update last login time on token obtain
    "UPDATE_LAST_LOGIN": True,
    # Cookie settings for web clients (refresh token stored in HttpOnly cookie)
    "AUTH_COOKIE": "refresh_token",
    "AUTH_COOKIE_DOMAIN": None,  # Set to your domain in production for cross-subdomain support
    "AUTH_COOKIE_SECURE": True,  # Only send cookie over HTTPS
    "AUTH_COOKIE_HTTP_ONLY": True,  # Prevent JavaScript access to cookie
    "AUTH_COOKIE_PATH": "/api/v1/auth/",  # Cookie only sent to auth endpoints
    "AUTH_COOKIE_SAMESITE": "Strict",  # Strict CSRF protection
}

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Logging configuration will be set up after environment-specific settings are loaded
# This placeholder will be overridden by the environment-specific configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Only Paws API",
    "DESCRIPTION": "The unapologetically pet friendly social media app.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "ENUM_NAME_OVERRIDES": {
        "PostReportStatusEnum": "apps.moderation_app.models.PostReport.ReportStatus",
        "FeedbackStatusEnum": "apps.feedback_app.models.Feedback.FeedbackStatus",
    },
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]",
}

UNFOLD = unfold_settings.UNFOLD


# Test Fixtures
FIXTURE_DIRS = [BASE_DIR / "fixtures"]

# Email Settings
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")

# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379/0")

# Cache configuration (uses Redis db 1 to avoid collision with Celery on db 0)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_CACHE_URL", "redis://redis:6379/1"),
    },
}
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

# Task routing and queue configuration
CELERY_TASK_DEFAULT_QUEUE = "default"

# Worker configuration
CELERY_WORKER_PREFETCH_MULTIPLIER = (
    1  # Only prefetch one task at a time for embedding workers
)
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion
CELERY_WORKER_MAX_TASKS_PER_CHILD = (
    50  # Restart workers after 50 tasks to prevent memory leaks
)

# Task result settings
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour
CELERY_TASK_IGNORE_RESULT = False  # Keep task results for monitoring

# Retry configuration
CELERY_TASK_RETRY_DELAY = 60  # Wait 60 seconds before retrying
CELERY_TASK_MAX_RETRIES = 3

# Celery Beat configuration
CELERY_BEAT_SCHEDULE_FILENAME = "/tmp/celerybeat-schedule"

# Celery Beat scheduled tasks
CELERY_BEAT_SCHEDULE = {
    "cleanup-old-notifications": {
        "task": "apps.notifications_app.tasks.cleanup_old_notifications_task",
        "schedule": crontab(hour=3, minute=0),  # Run daily at 3:00 AM UTC
        "args": (30,),  # Delete notifications older than 30 days
    },
    "flush-expired-jwt-tokens": {
        "task": "apps.core_app.tasks.flush_expired_tokens_task",
        "schedule": crontab(hour=4, minute=0),  # Run daily at 4:00 AM UTC
        "options": {"expires": 3600},  # Task expires after 1 hour if not picked up
    },
}

# Django Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")],
            "capacity": 1500,  # Maximum number of messages to store in a channel
            "expiry": 60,  # Message expiry time in seconds
        },
    },
}

# Get the current environment
environment: Literal["test", "e2e", "dev", "staging", "prod"] = os.environ.get(
    "DJANGO_ENV"
)

# Load the correct settings file based on the environment
if environment == "test":
    from core.settings_test import *

    print_environment_banner(environment)
elif environment == "e2e":
    from core.settings_e2e import *

    print_environment_banner(environment)
elif environment == "dev":
    from core.settings_dev import *

    print_environment_banner(environment)
elif environment == "staging":
    from core.settings_staging import *

    print_environment_banner(environment)
elif environment == "prod":
    from core.settings_prod import *

    print_environment_banner(environment)

# Configure logging after environment-specific settings are loaded
if environment:
    from core.logging_config import get_logging_config
    import logging.config

    LOGGING = get_logging_config(environment, log_dir="/vol/log")
    logging.config.dictConfig(LOGGING)
