# Generated by Django 5.1.1 on 2025-12-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=200)),
                ('message', models.TextField(help_text='Announcement message content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', help_text='Priority level of the announcement', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the announcement is active')),
                ('start_date', models.DateTimeField(help_text='When the announcement should start being displayed')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the announcement should stop being displayed (null = no end date)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the announcement was created')),
                ('announcement_type', models.CharField(default='general', help_text='Type of announcement (e.g., general, welcome, maintenance)', max_length=50)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='announcemen_is_acti_6f4e45_idx'), models.Index(fields=['announcement_type'], name='announcemen_announc_98e73a_idx'), models.Index(fields=['-priority', '-created_at'], name='announcemen_priorit_e2288f_idx')],
            },
        ),
    ]
