# Generated by Django 5.1.1 on 2025-10-30 16:27

import apps.posts_app.models
import django.core.validators
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000, message='Caption cannot exceed 1000 characters.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contains_ai', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.posts_app.models.post_image_path)),
                ('order', models.IntegerField(default=0, help_text='Display order of the image in the post')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='Vector embedding for similarity search', null=True)),
                ('embedding_model', models.CharField(default='clip-vit-base-patch32', help_text='Model used to generate the embedding', max_length=100)),
                ('embedding_generated_at', models.DateTimeField(blank=True, help_text='When the embedding was generated', null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
