# Generated by Django 5.1.1 on 2025-11-20 12:57

import apps.core_app.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_add_combined_embedding_to_post'),
        ('profile_app', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=apps.core_app.indexes.HnswIndex(ef_construction=200, fields=['combined_embedding'], m=32, name='post_comb_emb_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=apps.core_app.indexes.HnswIndex(ef_construction=200, fields=['embedding'], m=32, name='postimg_emb_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
