# Generated by Django 5.1.1 on 2025-11-22 22:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_post_post_comb_emb_hnsw_idx_and_more'),
        ('profile_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.DecimalField(decimal_places=2, help_text='X coordinate as percentage (0-100) of image width', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('y_position', models.DecimalField(decimal_places=2, help_text='Y coordinate as percentage (0-100) of image height', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='posts_app.postimage')),
                ('tagged_by_profile', models.ForeignKey(help_text='The profile that created this tag', on_delete=django.db.models.deletion.CASCADE, related_name='image_tags_created', to='profile_app.profile')),
                ('tagged_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_in_images', to='profile_app.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['post_image'], name='posts_app_p_post_im_68401c_idx'), models.Index(fields=['tagged_profile'], name='posts_app_p_tagged__60f9e3_idx')],
                'unique_together': {('post_image', 'tagged_profile')},
            },
        ),
    ]
