# Generated by Django 5.1.1 on 2025-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_postimagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aspect_ratio',
            field=models.CharField(choices=[('1:1', 'Square'), ('4:5', 'Portrait')], default='1:1', help_text='Aspect ratio for all images in this post', max_length=5),
        ),
    ]
