# Generated by Django 5.1.1 on 2026-02-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0011_public_id_default'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postimagescaled',
            new_name='posts_app_p_post_im_c85930_idx',
            old_name='posts_app_p_post_im_7c1a8b_idx',
        ),
        migrations.AlterField(
            model_name='postimagescaled',
            name='scale',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium')], max_length=20),
        ),
    ]
