# Generated by Django 5.2.12 on 2026-03-20 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0012_rename_posts_app_p_post_im_7c1a8b_idx_posts_app_p_post_im_c85930_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 20, 22, 51, 55, 965390, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
