# Generated by Django 5.2.12 on 2026-06-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0013_postimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='blurhash',
            field=models.CharField(blank=True, default='', help_text='BlurHash placeholder generated from this image', max_length=128),
        ),
    ]
